train :
    batch_size : 16
    max_epoch : 100
    shuffle : True
    learning_rate : 1e-5
    sweep : True
    num_workers : 8
    hidden_dropout_prob : 0.0
    attention_probs_dropout_prob: 0.0

inference :
    batch_size : 16
    max_epoch : 100
    shuffle : True
    learning_rate : 1e-5
    sweep : False
    num_workers : 8
    hidden_dropout_prob : 0.0
    attention_probs_dropout_prob: 0.0