train :
    batch_size : 16
    max_epoch : 100
    shuffle : True
    learning_rate : 1e-5
    sweep : True

inference :
    batch_size : 16
    max_epoch : 100
    shuffle : True
    learning_rate : 1e-5
    sweep : False