train :
    batch_size : 16
    max_epoch : 100
    shuffle : True
    learning_rate : 1e-5
    kfold : True
    sweep : False

inference :
    batch_size : 16
    max_epoch : 100
    shuffle : True
    learning_rate : 1e-5
    kfold : True
    sweep : False

model : 
    name : 'klue/roberta-small'
    train_path : './data/train.csv'
    dev_path : './data/dev.csv'
    test_path : './data/dev.csv'
    predict_path : './data/test.csv'