model_name : "klue/roberta-large"
seed : 42
callback : "val_loss"

train :
    batch_size : 8
    max_epoch : 100
    shuffle : True
    learning_rate : 1e-5
    sweep : False
    num_workers : 8
    hidden_dropout_prob : 0.1
    attention_probs_dropout_prob: 0.1

inference :
    batch_size : 8
    max_epoch : 100
    shuffle : True
    learning_rate : 1e-5
    sweep : False
    num_workers : 8
    hidden_dropout_prob : 0
    attention_probs_dropout_prob: 0

path : 
    train_path: "./data/train.csv"
    dev_path: "./data/dev.csv"
    test_path: "./data/dev.csv"
    predict_path: "./data/test.csv"
    
