model_name : "snunlp/KR-ELECTRA-discriminator"
seed : 42
callback : "val_pearson"

train :
    batch_size : 64
    max_epoch : 12
    shuffle : True
    learning_rate : 3e-5
    sweep : False
    num_workers : 8
    hidden_dropout_prob : 0.0
    attention_probs_dropout_prob: 0.0

inference :
    batch_size : 64
    max_epoch : 1
    shuffle : False
    learning_rate : 1e-5
    sweep : False
    num_workers : 8
    hidden_dropout_prob : 0.0
    attention_probs_dropout_prob: 0.0

path : 
    train_path: "./data/pos_2neg.csv"
    dev_path: "./data/dev.csv"
    test_path: "./data/dev.csv"
    predict_path: "./data/test.csv"
    
