model_name : "snunlp/KR-ELECTRA-discriminator"
seed : 42
callback : "val_pearson"
loss : "CorLoss"

train :
    batch_size : 32
    max_epoch : 5
    shuffle : True
    learning_rate : 3e-5
    sweep : False
    multi : True
    num_workers : 1
    hidden_dropout_prob : 0.0
    attention_probs_dropout_prob: 0.0

inference :
    batch_size : 32
    max_epoch : 1
    shuffle : True
    learning_rate : 3e-5
    sweep : True
    multi : True
    num_workers : 1
    hidden_dropout_prob : 0.0
    attention_probs_dropout_prob: 0.0

path : 
    train_path: "./data/train.csv"
    dev_path: "./data/dev.csv"
    test_path: "./data/dev.csv"
    predict_path: "./data/test.csv"
    
