model_nameA : "klue/roberta-base"
model_nameB : "xlm-roberta-base"
ensemble_model_name : "klue/roberta-base"
model_name : "xlm-roberta-base"
seed : 42
callback : "val_pearson"

train :
    batch_size : 16
    max_epoch : 1
    shuffle : True
    learning_rate : 1e-5
    sweep : True
    num_workers : 8
    hidden_dropout_prob : 0.0
    attention_probs_dropout_prob: 0.0

inference :
    batch_size : 16
    max_epoch : 1
    shuffle : True
    learning_rate : 1e-5
    sweep : False
    num_workers : 8
    hidden_dropout_prob : 0.0
    attention_probs_dropout_prob: 0.0

path : 
    train_path: "./data/train.csv"
    dev_path: "./data/dev.csv"
    test_path: "./data/dev.csv"
    predict_path: "./data/test.csv"
    
