method : 'random'
metric : 
  goal : 'minimize'
  name : 'val_loss'
parameters : 
  batch_size : 
    values :
      - 4
      - 8
      - 16
  max_epoch : 
    values :
      - 100
  learning_rate : 
    distribution: "uniform"  
    min : 1e-6      
    max : 1e-5
  shuffle : 
    values : 
      - True
  sweep : 
    values : 
      - True
  num_workers :
    values :
      - 8
  hidden_dropout_prob :
    distribution: "uniform"  
    min : 0.0   
    max : 0.3
  attention_probs_dropout_prob:
    distribution: "uniform"  
    min : 0.0   
    max : 0.3