method : 'random'
metric : 
  goal : 'minimize'
  name : 'val_loss'
parameters : 
  batch_size : 
    values :
      # - 4
      - 8
      # - 16
  max_epoch : 
    values :
      - 15
  learning_rate : 
    # distribution: "uniform"  
    # min : 1e-6      
    # max : 5e-6
    values :
      - 0.000004044712962140626
  shuffle : 
    values : 
      - True
  sweep : 
    values : 
      - True
  num_workers :
    values :
      - 16
  hidden_dropout_prob :
    # distribution: "uniform"  
    # min : 0.0   
    # max : 0.3
    values : 
      - 0.08718024404205035
  attention_probs_dropout_prob:
    # distribution: "uniform"  
    # min : 0.0   
    # max : 0.3
    values :
      - 0.24171740782584733